RANDOM_STATE : 42

ordinal_ranking_flat_type : 
- 'MULTI GENERATION'
- 'EXECUTIVE'
- '5 ROOM'
- '4 ROOM'
- '3 ROOM'
- '2 ROOM'
- '1 ROOM'

ordinal_ranking_storey_range : 
- '01 TO 03'
'01 TO 05'
 '04 TO 06'
 '06 TO 10'
 '07 TO 09'
 '10 TO 12'
 '11 TO 15'
 '13 TO 15'
 '16 TO 18'
'16 TO 20','19 TO 21','21 TO 25', '22 TO 24', '25 TO 27', '26 TO 30', '28 TO 30',
       '31 TO 33','31 TO 35','34 TO 36',  '37 TO 39', '36 TO 40', '40 TO 42', '43 TO 45', '46 TO 48','49 TO 51'